// packages/hive-vue/src/components/Container.vue
<script lang="ts">
import { ContainerSizeValues } from '@alexbjr369/hive-common';
import type { PropType } from 'vue';
import { computed, defineComponent, reactive } from 'vue';

interface HvContainerProps {
  size?: ContainerSizeValues;
}

export default defineComponent({
  name: 'hv-container',
  props: {
    size: {
      type: String as PropType<HvContainerProps>,
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      classes: computed(() => ({
        'hv-container': true,
        [`hv-container_${props.size}`]: props.size !== undefined,
      })),
    };
  },
});
</script>

<template>
  <div :class="classes">
    <slot></slot>
  </div>
</template>

<style></style>

// packages/hive-react/src/components/Container/index.tsx
import { ContainerSizeValues } from '@alexbjr369/hive-common';
import classNames from 'classnames';
import { ReactNode } from 'react';

interface HvContainerProps {
  size?: ContainerSizeValues;
  children?: ReactNode;
  className?: string;
}

export function HvContainer({ size, children, className }: HvContainerProps) {
  return (
    <div
      className={classNames({
        'hv-container': true,
        [`hv-container_${size}`]: size !== undefined,
        [`${className}`]: className !== undefined,
      })}
    >
      {children}
    </div>
  );
}
