// packages/hive-react/src/components/Container/index.tsx
import { ContainerSizeValues } from '@alexbjr369/hive-common';
import classNames from 'classnames';
import { ReactNode } from 'react';

interface HvContainerProps {
  size?: ContainerSizeValues;
  children?: ReactNode;
  className?: string;
}

export function HvContainer({ size, children, className }: HvContainerProps) {
  return (
    <div
      className={classNames({
        'hv-container': true,
        [`hv-container_${size}`]: size !== undefined,
        [`${className}`]: className !== undefined,
      })}
    >
      {children}
    </div>
  );
}

// packages/hive-angular/projects/hive/src/lib/container/container.component.ts
import { ContainerSizeValues } from '@alexbjr369/hive-common';
import { Component, HostBinding, Input, OnInit } from '@angular/core';
import classNames from 'classnames';

@Component({
  selector: 'hv-container',
  templateUrl: './container.component.html',
  styleUrls: ['./container.component.scss'],
})
export class HvContainer implements OnInit {
  @Input() size?: ContainerSizeValues;

  constructor() {}

  @HostBinding('class') get classes(): string {
    return classNames({
      'hv-container': true,
      [`hv-container_${this.size}`]: this.size !== undefined,
    });
  }

  ngOnInit(): void {}
}
