// packages/hive-angular/projects/hive/src/lib/container/container.component.ts
import { ContainerSizeValues } from '@alexbjr369/hive-common';
import { Component, HostBinding, Input, OnInit } from '@angular/core';
import classNames from 'classnames';

@Component({
  selector: 'hv-container',
  templateUrl: './container.component.html',
  styleUrls: ['./container.component.scss'],
})
export class HvContainer implements OnInit {
  @Input() size?: ContainerSizeValues;

  constructor() {}

  @HostBinding('class') get classes(): string {
    return classNames({
      'hv-container': true,
      [`hv-container_${this.size}`]: this.size !== undefined,
    });
  }

  ngOnInit(): void {}
}

// packages/hive-wc-core/src/components/container/container.tsx
import { ContainerSizeValues } from '@alexbjr369/hive-common';
import { Component, ComponentInterface, h, Host, Prop } from '@stencil/core';

@Component({
  tag: 'hv-container',
  styleUrl: 'container.scss',
  shadow: true,
})
export class Container implements ComponentInterface {
  /**
   * Defines the component size.
   */
  @Prop({ reflect: true }) size?: ContainerSizeValues;

  render() {
    const { size } = this;

    return (
      <Host
        class={{
          'hv-container': true,
          [`hv-container_${size}`]: size !== undefined,
        }}
      >
        <slot></slot>
      </Host>
    );
  }
}
